In [3]:
import pandas as pd
import numpy as np

import sklearn
from sklearn.ensemble import IsolationForest

In [4]:
df=pd.read_csv("iris(1).csv")

In [5]:
df

     Sepal.Length  Sepal.Width  Petal.Length  Petal.Width    Species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [6]:
finaldf= pd.get_dummies(df)

In [7]:
finaldf

,Sepal.Length,Sepal.Width,Petal.Length,Petal.Width,Species_setosa,Species_versicolor,Species_virginica
0,5.1,3.5,1.4,0.2,1,0,0
1,4.9,3.0,1.4,0.2,1,0,0
2,4.7,3.2,1.3,0.2,1,0,0
3,4.6,3.1,1.5,0.2,1,0,0
4,5.0,3.6,1.4,0.2,1,0,0
...,...,...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,0,0,1
146,6.3,2.5,5.0,1.9,0,0,1
147,6.5,3.0,5.2,2.0,0,0,1
148,6.2,3.4,5.4,2.3,0,0,1
149,5.9,3.0,5.1,1.8,0,0,1

In [8]:
model=IsolationForest(random_state=40,contamination=0.2)
model.fit(finaldf)

IsolationForest(contamination=0.2, random_state=40)

In [9]:
pred=model.predict(finaldf)
pred

array([ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1, -1, -1, -1,  1,
        1, -1,  1,  1,  1, -1, -1,  1,  1,  1,  1,  1,  1,  1,  1, -1, -1,
        1,  1,  1,  1,  1,  1,  1, -1,  1, -1, -1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1, -1,  1,  1, -1,  1, -1,  1,  1,  1,  1,  1,
       -1,  1, -1,  1,  1,  1,  1,  1,  1, -1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1, -1,  1,  1,  1,  1, -1,  1, -1,  1,
        1,  1,  1, -1, -1,  1,  1, -1,  1,  1,  1,  1,  1,  1,  1, -1, -1,
       -1,  1,  1, -1,  1,  1,  1,  1,  1,  1,  1,  1, -1,  1,  1, -1, -1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1])

In [24]:
finaldf['scores']=model.decision_function(finaldf)

ValueError: Number of features of the model must match the input. Model n_features is 7 and input n_features is 8.

In [25]:
finaldf

,Sepal.Length,Sepal.Width,Petal.Length,Petal.Width,Species_setosa,Species_versicolor,Species_virginica,scores
0,5.1,3.5,1.4,0.2,1,0,0,0.105822
1,4.9,3.0,1.4,0.2,1,0,0,0.075022
2,4.7,3.2,1.3,0.2,1,0,0,0.078077
3,4.6,3.1,1.5,0.2,1,0,0,0.059337
4,5.0,3.6,1.4,0.2,1,0,0,0.097787
...,...,...,...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,0,0,1,0.062836
146,6.3,2.5,5.0,1.9,0,0,1,0.045618
147,6.5,3.0,5.2,2.0,0,0,1,0.091401
148,6.2,3.4,5.4,2.3,0,0,1,0.015150
149,5.9,3.0,5.1,1.8,0,0,1,0.060688

In [29]:
finaldf['anomaly']=model.predict(finaldf.iloc[:,0:7])

In [30]:
finaldf[finaldf['anomaly']==-1]

,Sepal.Length,Sepal.Width,Petal.Length,Petal.Width,Species_setosa,Species_versicolor,Species_virginica,scores,anomaly
13,4.3,3.0,1.1,0.1,1,0,0,-0.103702,-1
14,5.8,4.0,1.2,0.2,1,0,0,-0.070047,-1
15,5.7,4.4,1.5,0.4,1,0,0,-0.082381,-1
18,5.7,3.8,1.7,0.3,1,0,0,-0.020210,-1
22,4.6,3.6,1.0,0.2,1,0,0,-0.046312,-1
23,5.1,3.3,1.7,0.5,1,0,0,-0.006845,-1
32,5.2,4.1,1.5,0.1,1,0,0,-0.047902,-1
33,5.5,4.2,1.4,0.2,1,0,0,-0.006652,-1
41,4.5,2.3,1.3,0.3,1,0,0,-0.096062,-1
43,5.0,3.5,1.6,0.6,1,0,0,-0.024970,-1
44,5.1,3.8,1.9,0.4,1,0,0,-0.013205,-1
57,4.9,2.4,3.3,1.0,0,1,0,-0.053921,-1
60,5.0,2.0,3.5,1.0,0,1,0,-0.071865,-1
62,6.0,2.2,4.0,1.0,0,1,0,-0.033130,-1
68,6.2,2.2,4.5,1.5,0,1,0,-0.008659,-1
70,5.9,3.2,4.8,1.8,0,1,0,-0.018988,-1
77,6.7,3.0,5.0,1.7,0,1,0,-0.013728,-1
93,5.0,2.3,3.3,1.0,0,1,0,-0.029626,-1
98,5.1,2.5,3.0,1.1,0,1,0,-0.043197,-1
100,6.3,3.3,6.0,2.5,0,0,1,-0.002036,-1
105,7.6,3.0,6.6,2.1,0,0,1,-0.006209,-1
106,4.9,2.5,4.5,1.7,0,0,1,-0.080380,-1
109,7.2,3.6,6.1,2.5,0,0,1,-0.053555,-1
117,7.7,3.8,6.7,2.2,0,0,1,-0.087505,-1
118,7.7,2.6,6.9,2.3,0,0,1,-0.094300,-1
119,6.0,2.2,5.0,1.5,0,0,1,-0.083802,-1
122,7.7,2.8,6.7,2.0,0,0,1,-0.022014,-1
131,7.9,3.8,6.4,2.0,0,0,1,-0.109874,-1
134,6.1,2.6,5.6,1.4,0,0,1,-0.033763,-1
135,7.7,3.0,6.1,2.3,0,0,1,-0.000402,-1

In [35]:
pip install ppscore

Collecting ppscore
  Downloading ppscore-1.2.0.tar.gz (47 kB)
Requirement already satisfied: pandas<2.0.0,>=1.0.0 in c:\users\apeksha\anaconda3\lib\site-packages (from ppscore) (1.3.4)
Requirement already satisfied: scikit-learn<1.0.0,>=0.20.2 in c:\users\apeksha\anaconda3\lib\site-packages (from ppscore) (0.24.2)
Requirement already satisfied: python-dateutil>=2.7.3 in c:\users\apeksha\anaconda3\lib\site-packages (from pandas<2.0.0,>=1.0.0->ppscore) (2.8.2)
Requirement already satisfied: numpy>=1.17.3 in c:\users\apeksha\anaconda3\lib\site-packages (from pandas<2.0.0,>=1.0.0->ppscore) (1.20.3)
Requirement already satisfied: pytz>=2017.3 in c:\users\apeksha\anaconda3\lib\site-packages (from pandas<2.0.0,>=1.0.0->ppscore) (2021.3)
Requirement already satisfied: six>=1.5 in c:\users\apeksha\anaconda3\lib\site-packages (from python-dateutil>=2.7.3->pandas<2.0.0,>=1.0.0->ppscore) (1.16.0)
Requirement already satisfied: joblib>=0.11 in c:\users\apeksha\anaconda3\lib\site-packages (from scikit-learn<1.0.0,>=0.20.2->ppscore) (1.1.0)
Requirement already satisfied: threadpoolctl>=2.0.0 in c:\users\apeksha\anaconda3\lib\site-packages (from scikit-learn<1.0.0,>=0.20.2->ppscore) (2.2.0)
Requirement already satisfied: scipy>=0.19.1 in c:\users\apeksha\anaconda3\lib\site-packages (from scikit-learn<1.0.0,>=0.20.2->ppscore) (1.7.1)
Building wheels for collected packages: ppscore
  Building wheel for ppscore (setup.py): started
  Building wheel for ppscore (setup.py): finished with status 'done'
  Created wheel for ppscore: filename=ppscore-1.2.0-py2.py3-none-any.whl size=13068 sha256=2c00bee194ffca0f4bbac77daed33dcfcce820fa745ce0391537bf88c2b19024
  Stored in directory: c:\users\apeksha\appdata\local\pip\cache\wheels\66\5f\af\a0de66f8359588661c0b1239580f4788dba33a4a1e504ef682
Successfully built ppscore
Installing collected packages: ppscore
Successfully installed ppscore-1.2.0
Note: you may need to restart the kernel to use updated packages.

In [36]:
import ppscore as pps

In [37]:
pps.matrix(finaldf)

,x,y,ppscore,case,is_valid_score,metric,baseline_score,model_score,model
0,Sepal.Length,Sepal.Length,1.000000,predict_itself,True,None,0.000000,1.000000,None
1,Sepal.Length,Sepal.Width,0.000000,regression,True,mean absolute error,0.330667,0.364704,DecisionTreeRegressor()
2,Sepal.Length,Petal.Length,0.550423,regression,True,mean absolute error,1.488667,0.669271,DecisionTreeRegressor()
3,Sepal.Length,Petal.Width,0.431739,regression,True,mean absolute error,0.644667,0.366339,DecisionTreeRegressor()
4,Sepal.Length,Species_setosa,0.499037,regression,True,mean absolute error,0.333333,0.166988,DecisionTreeRegressor()
...,...,...,...,...,...,...,...,...,...
76,anomaly,Species_setosa,0.000000,regression,True,mean absolute error,0.333333,0.452774,DecisionTreeRegressor()
77,anomaly,Species_versicolor,0.000000,regression,True,mean absolute error,0.333333,0.447715,DecisionTreeRegressor()
78,anomaly,Species_virginica,0.000000,regression,True,mean absolute error,0.333333,0.447564,DecisionTreeRegressor()
79,anomaly,scores,0.344141,regression,True,mean absolute error,0.038578,0.025302,DecisionTreeRegressor()
80,anomaly,anomaly,1.000000,predict_itself,True,None,0.000000,1.000000,None

In [39]:
pps.score(finaldf,"Sepal.Length","Sepal.Width")

{'x': 'Sepal.Length',
 'y': 'Sepal.Width',
 'ppscore': 0,
 'case': 'regression',
 'is_valid_score': True,
 'metric': 'mean absolute error',
 'baseline_score': 0.33066666666666666,
 'model_score': 0.3647043707241076,
 'model': DecisionTreeRegressor()}